(function(){var j,k;function v(){var a=$("div#background"),b=a.find("img");q||(q=b.height()/b.width());var c=$(window).width();c<D&&(c=800);var e=q*c;b.width(c).height(e);a.height($("body").height());a=$("canvas");r||(h=a.width(),l=a.height(),r=a.height()/h);b=$("#main").width();c=r*b;a.attr("width",b).attr("height",c);j=b;k=c;s=b/h}function m(a,b){this.x=a;this.y=b;this.getX=function(){return this.x*s};this.getY=function(){return this.y*s};this.X=function(){return this.getX()};this.Y=function(){return this.getY()}}
function i(a,b){this.from=a;this.to=b;this.times=0;this.speed=(new NormalDistribution(0.11*w,(this.to>this.from?1:-1)*0.2*w)).sample();this.aspeed=Math.abs(this.speed);this.position=a;this.lastDifference=h}function t(a,b,c){this.originalPoints=[];var e=this;$.each(a,function(a,b){e.originalPoints.push(new m(b.x,b.y))});this.points=a;this.xmovements=[];this.ymovements=[];this.weight=b;this.weightMovement=null;this.opacity=c;this.evolve()}function x(){this.curves=[];var a;a=E;for(var b=h*0.01,c=l*0.1,
e=l*0.5,d=(h+100)/(a-1),g=[],f=-50,i=0;i<a;i++){var j=(new NormalDistribution(b,f)).sample();f+=d;var k=(new NormalDistribution(c,e)).sample();g.push(new m(j,k))}a=(new NormalDistribution(n,n)).sample();b=(new NormalDistribution(0.5,0.5)).sample();b<o?b=o:b>p&&(b=p);a=new t(g,a,b);this.curves.push(a);for(g=1;g<F;g++){b=a.points;c=b.length;a=[];for(e=0;e<c;e++)f=b[e],d=(new NormalDistribution(h*0.01,f.x)).sample(),f=(new NormalDistribution(l*0.08,f.y)).sample(),a.push(new m(d,f));b=(new NormalDistribution(n,
n)).sample();if(b<1||Math.random()>0.8)b=1;c=(new NormalDistribution(0.2,0.2)).sample();c<o?c=o:c>p&&(c=p);a=new t(a,b,c);this.curves.push(a)}}function y(){this.canvas=$("canvas")[0];this.strips=[];this.timerHandler=null;for(var a=0;a<G;a++)this.strips.push(new x);z=(new Date).getTime();this.draw();this.animate()}var q=null,r=null,s=null,h=null,l=null,D=800,E=5,w=0.3,G=3,F=6,n=14,o=0.1,p=0.3,A=null,u=-1,B=0,z=0,C=null;j=0;k=0;$.extend(i.prototype,{getPosition:function(){return this.position},move:function(){this.position+=
this.speed;var a=Math.abs(this.to-this.position);if(a>this.lastDifference)return null;this.times++;this.lastDifference=a;return this}});$.extend(t.prototype,{getPoint:function(a){return this.points[a]},computeControlPoints:function(){this.firstControlPoints=[];this.secondControlPoints=[];var a=this,b=[],c=[];A.GetCurveControlPoints(this.points,b,c);$.each(b,function(b,c){a.firstControlPoints.push(new m(c.x,c.y))});$.each(c,function(b,c){a.secondControlPoints.push(new m(c.x,c.y))})},evolve:function(){for(var a=
this.points.length,b=0;b<a;b++){var c=this.ymovements[b];this.xmovements[b]||(this.xmovements[b]=this.generateXMovement(b));c||(this.ymovements[b]=this.generateYMovement(b))}for(b=0;b<a;b++)c=this.points[b],c.x=this.xmovements[b].getPosition(),c.y=this.ymovements[b].getPosition(),this.xmovements[b]=this.xmovements[b].move(),this.ymovements[b]=this.ymovements[b].move();this.computeControlPoints();this.alterWeight()},alterWeight:function(){if(!this.weightMovement){var a=(new NormalDistribution(n,this.weight)).sample();
a<1?a=1:a>40&&(a=40);this.weightMovement=new i(this.weight,a)}this.weight=this.weightMovement.getPosition();this.weightMovement=this.weightMovement.move()},generateXMovement:function(a){var b=(new NormalDistribution(h*0.01,this.originalPoints[a].x)).sample();return new i(this.points[a].x,b)},generateYMovement:function(a){var b=(new NormalDistribution(l*0.13,this.originalPoints[a].y)).sample();return new i(this.points[a].y,b)},draw:function(a){var b;a.beginPath();a.moveTo((b=this.getPoint(0)).getX(),
b.getY());b=1;for(var c=this.points.length,e=0;b<c;b++){var d=this.points[b],g=this.firstControlPoints[e],f=this.secondControlPoints[e++];a.bezierCurveTo(g.getX(),g.getY(),f.getX(),f.getY(),d.getX(),d.getY())}b=a.createLinearGradient(0,0,0,150);b.addColorStop(0,"#26C000");b.addColorStop(1,"#fff");a.strokeStyle=b;a.lineWidth=this.weight;a.globalAlpha=this.opacity;a.stroke();a.closePath()},evolveByRelativeDisplacement:function(a,b){for(var c=0,e=this.points.length;c<e;c++){var d=this.points[c];d.x+=
Math.random()>0.5?a[c]:0;d.y+=Math.random()>0.5?b[c]:0}this.computeControlPoints();this.alterWeight()}});$.extend(x.prototype,{draw:function(a){$.each(this.curves,function(b,c){c.draw(a)})},evolve:function(){for(var a=[],b=[],c=this.curves[0],e=c.points.length,d=0;d<e;d++)a.push(c.points[d].x),b.push(c.points[d].y);c.evolve();for(var g=[],f=[],d=0;d<e;d++)g.push(c.points[d].x-a[d]),f.push(c.points[d].y-b[d]);for(d=1,e=this.curves.length;d<e;d++)this.curves[d].evolveByRelativeDisplacement(g,f)}});
(function(){$(document).ready(function(){window.setTimeout(function(){v();$("canvas")[0].getContext&&(A=new BezierSpline,C=new y)},100)});$(window).resize(v)})();$.extend(y.prototype,{animate:function(){var a=this;this.timerHandler=window.setInterval(function(){a.evolveStrip();a.draw()},33)},draw:function(){var a=this.canvas.getContext("2d");a.clearRect(0,0,j,k);$.each(this.strips,function(b,e){e.draw(a)});var b=((new Date).getTime()-z)/1E3;b>3&&u<20&&this.disableBackgroundAnimation();B++;u=B/b;$("#FPS").html(u)},
evolveStrip:function(){for(var a=0,b=this.strips.length;a<b;a++)this.strips[a].evolve()},disableBackgroundAnimation:function(){window.clearInterval(this.timerHandler);$("#FPS").parent().hide();$("#running_low").show();$(window).resize(function(){C.draw()})}})})();
